version: "3.3"
services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mariadb
    links:
      - mariadb
    
