version: "3"
services:
  db:
    image: mariadb
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1
      MYSQL_DATABASE: mysqltest
      MYSQL_PASSWORD: 1
      MYSQL_USER: alexandr
  web:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db
    links:
      - db
    
